AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 8

Metrics/ClassLength:
  Max: 500
